BEGIN;

-- Drop in reverse dependency order so this script can be re-run safely.
DROP TABLE IF EXISTS post_tags CASCADE;
DROP TABLE IF EXISTS chat_messages CASCADE;
DROP TABLE IF EXISTS answers CASCADE;
DROP TABLE IF EXISTS votes CASCADE;
DROP TABLE IF EXISTS reports CASCADE;
DROP TABLE IF EXISTS posts CASCADE;
DROP TABLE IF EXISTS pdf_files CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS chat_sessions CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS alembic_version CASCADE;

DROP TYPE IF EXISTS chat_role_enum CASCADE;
DROP TYPE IF EXISTS target_type_enum CASCADE;
DROP TYPE IF EXISTS user_role_enum CASCADE;
DROP TYPE IF EXISTS jenis_kelamin_enum CASCADE;

-- PostgreSQL enum types for Supabase.
CREATE TYPE jenis_kelamin_enum AS ENUM ('L', 'P');
CREATE TYPE user_role_enum AS ENUM ('user', 'admin');
CREATE TYPE target_type_enum AS ENUM ('post', 'answer');
CREATE TYPE chat_role_enum AS ENUM ('user', 'assistant');

-- Matches the table present in statistikita_db_with_dummy.sql.
CREATE TABLE alembic_version (
    version_num VARCHAR(32) PRIMARY KEY
);

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_lengkap VARCHAR(100) NOT NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(120) UNIQUE,
    jenis_kelamin jenis_kelamin_enum,
    password_hash VARCHAR(255),
    role user_role_enum NOT NULL,
    google_id VARCHAR(100) UNIQUE,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    is_active BOOLEAN,
    avatar_url VARCHAR(255)
);

CREATE TABLE tags (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE chat_sessions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(200),
    created_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE notifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type VARCHAR(50) NOT NULL,
    message TEXT NOT NULL,
    is_read BOOLEAN,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    ref_id INTEGER
);

CREATE TABLE pdf_files (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename VARCHAR(255) NOT NULL UNIQUE,
    original_name VARCHAR(255) NOT NULL,
    uploaded_at TIMESTAMP WITHOUT TIME ZONE,
    uploaded_by INTEGER REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE posts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    judul VARCHAR(255) NOT NULL,
    deskripsi TEXT NOT NULL,
    file_path VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    is_hidden BOOLEAN
);

CREATE TABLE reports (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    target_type target_type_enum NOT NULL,
    target_id INTEGER NOT NULL,
    isi_laporan TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE votes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    target_type target_type_enum NOT NULL,
    target_id INTEGER NOT NULL,
    value INTEGER NOT NULL,
    CONSTRAINT uq_user_vote UNIQUE (user_id, target_type, target_id)
);

CREATE TABLE answers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE chat_messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id INTEGER NOT NULL REFERENCES chat_sessions(id) ON DELETE CASCADE,
    role chat_role_enum NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE post_tags (
    post_id INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    tag_id INTEGER NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (post_id, tag_id)
);

-- Indexes equivalent to the MySQL dump.
CREATE INDEX idx_answers_post_id ON answers(post_id);
CREATE INDEX idx_answers_user_id ON answers(user_id);

CREATE INDEX idx_chat_messages_session_id ON chat_messages(session_id);

CREATE INDEX idx_chat_sessions_user_id ON chat_sessions(user_id);

CREATE INDEX idx_notifications_user_id ON notifications(user_id);

CREATE INDEX idx_pdf_files_uploaded_by ON pdf_files(uploaded_by);

CREATE INDEX idx_posts_user_id ON posts(user_id);

CREATE INDEX idx_post_tags_tag_id ON post_tags(tag_id);

CREATE INDEX idx_reports_user_id ON reports(user_id);

COMMIT;
